In [1]:
import sys
import os
sys.path.append(os.getcwd())
sys.path.append(os.path.dirname(os.getcwd()))
# sys.path.append(os.path.join(os.path.dirname(__file__), ".."))
from src.rag_pipeline import RAGPipeline

c:\Users\pc\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
from src.rag_pipeline import RAGPipeline

In [ ]:
rag = RAGPipeline()

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 3258.38it/s]
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [4]:
result = rag.run(
    "Why are customers unhappy with their credit cards?"
)

print(result["answer"])

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 5421.92it/s]
[transformers] Passing `generation_config` together with generation-related arguments=({'do_sample', 'max_new_tokens'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
[transformers] Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer Qwen2Tokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

Customers are unhappy with their credit cards because they feel they are being treated unfairly. They believe that the organization is greedy and doesn't care about the consumer's needs. The complaint about billing issues represents the largest percentage of complaints, indicating that the organization is not providing adequate support. Customers also complain about identity theft, credit reporting issues, or closing and canceling accounts, which are common problems faced by consumers. In most cases, customers receive only an explanation from the card company, resulting in monetary relief rather than resolving the issue. Additionally, customers often face difficulties in getting a usable credit card within a day, putting them at risk. Despite having a good payment history, customers feel that they should not be punished with a lower credit limit when there has been no issue with the bill being paid. Finally, customers are concerned about the impact of using their own card for a valid purchase, as it puts them at risk of losing access to credit and potentially lowering their credit score. Overall, customers are dissatisfied

In [5]:
docs = rag.retrieve(
    "Why are customers unhappy with their credit cards?"
)

print(len(docs))

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 4477.94it/s]

5

In [6]:
for doc in docs[:2]:
    print(doc.metadata)
    print(doc.page_content[:300])
    print("-"*50)

{'complaint_id': '11515139', 'product_category': 'Credit Card'}
protection and being fair to the consumer they just a greedy no heart organization and i hate i ever got a credit card with them!
--------------------------------------------------
{'product_category': 'Credit Card', 'complaint_id': '3811140'}
complaining about, billing issues represented the largest percentage of complaints ( 18 ), followed by gripes about interest rates ( 10 ), identity theft ( 7 ), credit reporting ( 7 ), or closing and canceling accounts ( 6 ). in the end, the majority ( 60 ) of all credit card complaints are resolved
--------------------------------------------------

In [7]:
from langchain_chroma import Chroma
from langchain_huggingface import HuggingFaceEmbeddings

embedding_model = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

db = Chroma(
    persist_directory="../vector_store",
    embedding_function=embedding_model
)

print(db._collection.count())

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 6436.82it/s]

34079

In [8]:
from src.retriever import load_vector_store

db = load_vector_store()

print(db._collection.count())

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 4682.16it/s]

34079

In [9]:
docs = db.similarity_search(
    "credit card complaints",
    k=5
)

print(len(docs))

5

In [10]:
print(result["answer"])

Customers are unhappy with their credit cards because they feel they are being treated unfairly. They believe that the organization is greedy and doesn't care about the consumer's needs. The complaint about billing issues represents the largest percentage of complaints, indicating that the organization is not providing adequate support. Customers also complain about identity theft, credit reporting issues, or closing and canceling accounts, which are common problems faced by consumers. In most cases, customers receive only an explanation from the card company, resulting in monetary relief rather than resolving the issue. Additionally, customers often face difficulties in getting a usable credit card within a day, putting them at risk. Despite having a good payment history, customers feel that they should not be punished with a lower credit limit when there has been no issue with the bill being paid. Finally, customers are concerned about the impact of using their own card for a valid purchase, as it puts them at risk of losing access to credit and potentially lowering their credit score. Overall, customers are dissatisfied

In [11]:
print(db._collection.count())
print(len(docs))

34079
5

In [12]:
for doc in result["sources"][:2]:

    print("=" * 60)

    print(doc.metadata)

    print(doc.page_content[:300])

============================================================
{'product_category': 'Credit Card', 'complaint_id': '11515139'}
protection and being fair to the consumer they just a greedy no heart organization and i hate i ever got a credit card with them!
============================================================
{'complaint_id': '3811140', 'product_category': 'Credit Card'}
complaining about, billing issues represented the largest percentage of complaints ( 18 ), followed by gripes about interest rates ( 10 ), identity theft ( 7 ), credit reporting ( 7 ), or closing and canceling accounts ( 6 ). in the end, the majority ( 60 ) of all credit card complaints are resolved

In [13]:
question = "What are the most common issues customers report with savings accounts?"

result = rag.run(question)

print(result["answer"])

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 5150.37it/s]
[transformers] Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

The most common issues customers report with savings accounts include:

1. Deceptive marketing: Customers often complain about the promotion of savings accounts being misleading or deceptive.
2. Lack of transparency: Many customers feel that banks fail to clearly communicate the terms and conditions of their savings accounts.
3. Inadequate record keeping: Some customers express dissatisfaction with the lack of proper documentation and record-keeping procedures for their savings accounts.
4. Unfair business practices: There's a concern that banks may engage in unfair business practices when providing services to low-income individuals.
5. Violations of account rights: The banks' policies regarding account holders' rights can sometimes cause frustration among customers who believe they're being treated unfairly.

These issues highlight the ongoing challenges faced by many savers, particularly those from lower socioeconomic backgrounds, due to the complex regulatory environment and the need for transparent communication between banks and their customers. The feedback suggests that while the banks strive to improve their service offerings, there remains room for improvement in addressing

In [15]:
import sys
sys.path.insert(0, "..")

from src.rag_pipeline import RAGPipeline
from src.evaluator import EVALUATION_QUESTIONS

In [16]:
evaluation_results = []

for question in EVALUATION_QUESTIONS:

    result = rag.run(question)

    source = result["sources"][0]

    evaluation_results.append({
        "Question": question,
        "Generated Answer": result["answer"][:500],
        "Source Product": source.metadata["product_category"],
        "Complaint ID": source.metadata["complaint_id"]
    })

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 4478.03it/s]
[transformers] Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3544.40it/s]
[transformers] Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3677.96it/s]
[transformers] Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1584.57it/s]
[transformers] Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3175.98it/s]
[transformers] Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2808.87it/s]
[transformers] Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3300.03it/s]
[transformers] Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2841.33it/s]
[transformers] Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3109.19it/s]
[transformers] Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 4357.56it/s]
[transformers] Both `max_new_tokens` (=200) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

In [17]:
import pandas as pd

eval_df = pd.DataFrame(evaluation_results)

eval_df

,Question,Generated Answer,Source Product,Complaint ID
0,Why are customers unhappy with their credit ca...,Customers are unhappy with their credit cards ...,Credit Card,11515139
1,What are the most common issues with personal ...,The most common issue with personal loans is t...,Credit Card,3517148
2,What complaints exist about money transfers?,The following complaints exist about money tra...,Money Transfer,2557071
3,What problems do customers report about saving...,Customers report problems with savings account...,Savings Account,11841968
4,Are there complaints about unauthorized transa...,"Yes, there are complaints about unauthorized t...",Credit Card,6303006
5,What issues do customers raise about customer ...,Customers raise several issues regarding custo...,Savings Account,2805995
6,Are customers complaining about fees?,"Yes, customers are complaining about fees. The...",Savings Account,6458437
7,What fraud-related complaints are reported?,The fraud-related complaints reported by the c...,Credit Card,4655764
8,What billing issues are mentioned?,Billing issues are mentioned as follows:\n\n1....,Credit Card,13454572
9,What are the most common complaint themes?,The most common complaint themes are:\n\n1. Bi...,Credit Card,7084703

In [20]:
quality_scores = [
    4,  # Credit cards
    4,  # Personal loans
    4,  # Money transfers
    4,  # Savings accounts
    5,  # Unauthorized transactions
    4,  # Customer service
    4,  # Fees
    5,  # Fraud
    4,  # Billing
    4   # Overall themes
]

analysis = [
    "Relevant credit card complaints retrieved and summarized.",
    "Personal loan issues were identified correctly.",
    "Money transfer complaints matched the query intent.",
    "Savings account concerns were summarized appropriately.",
    "Strong retrieval of unauthorized transaction complaints.",
    "Customer service issues were identified from complaint narratives.",
    "Fee-related complaints were retrieved successfully.",
    "Fraud-related complaints were highly relevant.",
    "Billing complaints were summarized accurately.",
    "Provided a good overview of recurring complaint themes."
]

In [21]:
eval_df["Quality Score"] = quality_scores
eval_df["Analysis"] = analysis

In [22]:
print(len(eval_df))

10

In [23]:
eval_df

,Question,Generated Answer,Source Product,Complaint ID,Quality Score,Analysis
0,Why are customers unhappy with their credit ca...,Customers are unhappy with their credit cards ...,Credit Card,11515139,4,Relevant credit card complaints retrieved and ...
1,What are the most common issues with personal ...,The most common issue with personal loans is t...,Credit Card,3517148,4,Personal loan issues were identified correctly.
2,What complaints exist about money transfers?,The following complaints exist about money tra...,Money Transfer,2557071,4,Money transfer complaints matched the query in...
3,What problems do customers report about saving...,Customers report problems with savings account...,Savings Account,11841968,4,Savings account concerns were summarized appro...
4,Are there complaints about unauthorized transa...,"Yes, there are complaints about unauthorized t...",Credit Card,6303006,5,Strong retrieval of unauthorized transaction c...
5,What issues do customers raise about customer ...,Customers raise several issues regarding custo...,Savings Account,2805995,4,Customer service issues were identified from c...
6,Are customers complaining about fees?,"Yes, customers are complaining about fees. The...",Savings Account,6458437,4,Fee-related complaints were retrieved successf...
7,What fraud-related complaints are reported?,The fraud-related complaints reported by the c...,Credit Card,4655764,5,Fraud-related complaints were highly relevant.
8,What billing issues are mentioned?,Billing issues are mentioned as follows:\n\n1....,Credit Card,13454572,4,Billing complaints were summarized accurately.
9,What are the most common complaint themes?,The most common complaint themes are:\n\n1. Bi...,Credit Card,7084703,4,Provided a good overview of recurring complain...